# Generated by Django 2.2 on 2019-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_another_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='Hello-World'),
            preserve_default=False,
        ),
    ]
