# Generated by Django 2.2 on 2019-10-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190920_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
